name       : ppp
version    : 2.4.7
release    : 2
source     :
    - https://download.samba.org/pub/ppp/ppp-2.4.7.tar.gz : 02e0a3dd3e4799e33103f70ec7df75348c8540966ee7c948e4ed8a42bbccfb30
license    :
    - BSD-3-Clause
    - GPL-2.0
component  : network.util
summary    : an open source package which implements the Point-to-Point Protocol (PPP) on Linux and Solaris systems
description: |
    an open source package which implements the Point-to-Point Protocol (PPP) on Linux and Solaris systems
builddeps  :
    - libpcap-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install DESTDIR=$installdir/usr
