name       : ppp
version    : 2.4.8
release    : 7
source     :
    - https://download.samba.org/pub/ppp/ppp-2.4.8.tar.gz : f6bf89beae26b2943dff8f1003533d6a5a4909a0fa6edfbec44fe039bbe61bc6
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
component  : network.util
summary    : an open source package which implements the Point-to-Point Protocol (PPP) on Linux and Solaris systems
description: |
    an open source package which implements the Point-to-Point Protocol (PPP) on Linux and Solaris systems
builddeps  :
    - pkgconfig(libpcap)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install DESTDIR=$installdir/usr
